### ISSUE TITLE
Error message when creating final map with QGIS 2.18

### ISSUE THREAD

**Issue by Kolliv** [Paprika-plugins/PaPRIKa#11]
This is error message of final map computation using QGIS 2.18 : 

    dst_ds_Carte_Finale = driver_Carte_Finale.CreateCopy(str(doss)+'/Vulnerability_Map.tif', src_ds_Carte_Finale, 0 )
			  File "C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages\osgeo\gdal.py", line 1507, in CreateCopy
			    return _gdal.Driver_CreateCopy(self, *args, **kwargs)
			ValueError: Received a NULL pointer.

We need to fix it rapidly !

**Comment by Yolecomte** [comment]
Ok, I will check that! Can you send me all your data? (Catchment area, dem, karst features,...)

**Comment by Kolliv** [comment]
Comment ça se fait que je ne peux pas labéllisé les issue ?
J'ai utilisé les données de FV, pour vérifier s'il s'agissat bien d'un problème de logiciel et non de données, donc en principe du les as ! pourquoi tu attribue ça as peprika 1.1 ? il faut fixer ce bug rapidement ...

**Comment by Yolecomte** [comment]
Comprend pas... Chez moi aucun souci... Tu utilises bien la version en cours du plugin? (pas celle du dépôts des extensions)

**Comment by Yolecomte** [comment]
See commit https://github.com/Yolecomte/PaPRIKa/commit/c1fabcf197abc205294c025e7fee28aa0080cdab

**Comment by Yolecomte** [comment]
Need to Be test to ensure the compatibility with 2.14
