### ISSUE TITLE
Problème de lecture MNT, critère I

### ISSUE THREAD

**Issue by enzociva** [Paprika-plugins/PaPRIKa#13]
Bonjour, je travaille sous Qgis 2.18.4 et j'ai un problème dans la génération de ma carte I. Le raster I factor se crée mais est partiellement vide. La génération à partir des phénomènes exokarstiques marche mais aucune des données liées à la pente n'est prise en compte. Le log OGR donne comme message : "1	Source de données invalide ()". J'ai renseigné un MNT au format asc qui est valide. Si quelqu'un a rencontré ce problème je suis preneur d'information.

**Comment by Yolecomte** [comment]
Bonjour j'arrive à reproduire avec le MNT que vous m'avez fourni... Il y a effectivement un problème que je ne m'explique pas. je suis sur le coup et vous tiens informé.
Le problème vient de la carte de pente générée par GDAL qui n'est pas relue correctement par l'algorithme de reclassement... C'est d'autant plus étrange que si je réalise les opérations à la main ça fonctionne.

**Comment by enzociva** [comment]
Ok je télécharge un autre MNT plus précis mais si vous arrivez à produire la carte I manuellement je suppose que ca ne vient pas du MNT. A la limite je veux bien les commandes python des fonctions à exécuter pour créer I_Factor en attendant histoire de pouvoir avancer mes cartes.

**Comment by Yolecomte** [comment]
Bon je commence a contraindre le problème. Il s'agit d'un problème côté framework processing.
C'est l'algorithme GRASS7 r:reclass (utilisé pour passer de la carte des pentes aux 4 classes de vulnérabilité) qui pour une raison que j'ignore, se lance avec un paramètre projection en WGS84 avec ton MNT... En vrai, les données sont en L93 donc fatalement ça coince... 
J'ai réussi à faire tourner l'ensemble en partant d'un projet vierge avec ton MNT (convertis en GeoTIFF - L93 pour être sur), l'impluvium et le raster guide. Le SCR du projet en L93 (EPSG:2154) sans projection à la volée.
Dans ces conditions ca marche chez moi... En gros, il semble qu'il faille triple checker que tout est bien dans un CRS cohérent et ça marche. C'est assez étrange que processing n'arrive pas à récuperer le bon CRS dans tous les cas de figures. 

Pour les versions ne passe pas sur QGIS3. Le plugin n'est pas encore porté vers cette version car cela demande pas mal de travail (passage a python3 et PyQt5). C'est en cours de négociation pour financement. Le plugin est conçu pour tourner sous QGIS 2.14 - 2.18 donc pas de problème de ce côté là... Pour le coup ça ressemble plus à un bug de processing. Je fouillerai plus en détail et si ça me parait opportun j'ouvrirai un ticket sur QGIS.  

Merci de me confirmer que tu arrives bien à résoudre en passant par un nouveau projet full L93 et sans projection à la volée.

**Comment by enzociva** [comment]
J'ai bien désactivé la projection à la volée et tout mis en EPSG:2154, rien n'y fait j'ai toujours "Source de données invalides". Je vais essayer depuis une autre machine ce soir je préviens si ca marche ou pas. On est d'accord que le plugin Paprika de la biblio qgis est fonctionnel ?

**Comment by Yolecomte** [comment]
Oui c'est bien le plugin du dépôt officiel qu'il faut utiliser (actuellement en version 1.1).
Voila les étapes qui me permettent de le faire fonctionner avec vos données:
1) enregistrement du MNT .asc en format Geotiff, projection EPSG:2154.
2) nouveau projet EPSG:2154, pas de projection à la volée.
3) création du guide a partir d'un impluvium vecteur en EPSG:2154.
4) création de la carte I depuis le plugin avec le MNT convertis. 

et j'obtiens bien le raster des pentes reclassées. 

Sous quel OS vous travaillez?

**Comment by Yolecomte** [comment]
Content que ça soit résolu. Il semble en effet qu'il y ai eu qqc de défectueux avec le premier mnt. Je testerai sur d'autre dalles IGN pour voir si le problème se généralise sur tout leur fichier ASCII. 
En tout cas merci pour le retour et bon courage pour la suite en espérant que tout fonctionne bien. Sinon n'hésitez pas à rouvrir un ticket, comme je le disais cet outil à encore peu été soumis aux utilisateurs.
