### ISSUE TITLE
Qgis 3

### ISSUE THREAD

**Issue by sylsta** [Paprika-plugins/PaPRIKa#14]
Hello, 
Has-it been plan to modify the extension for it to be compatible with python 3 & QGIS 3 ?

All the best.
S.

**Comment by Yolecomte** [comment]
Hi,
Yes, we are discussing it at the moment but we lack financial means to do the migrations... For now, you Can use the paprika toolbox with qgis2.14 or 2.18. Some improvements on docs are also planned. Just waiting for some financial support...

**Comment by sylsta** [comment]
Yes, of course, that's the point. I use to work with Valérie Plagnes at waht has  become Paprika (first by the middle of the 2000's it was called RISKE then RISKPE :) and then the BRGM asked (and payed for a unique version). 
Last Friday, I've asked Valérie about the possibility of founding by our lab, and I'm afraid it's gonna be hard. 
As far as I'm really interested in porting the plugin into python3, would it possible to create a new branch ? Of course, I could do it on my fork, but I think it would be easier ton merge potential commits if the branch is set on the main stream of the code.

All the best.

**Comment by Yolecomte** [comment]
Ah interesting!
I start developing this tool during an internship at Syndicat Mixte du Bassin des Sorgues and UMR EMMAH near Avignon. I was working on applying the Paprika method on the Fontaine de Vaucluse catchment area (I can send you my internship report if you're interested :). As the work progress, it appears that the GIS technical part of the job was not straight-forward to do and too much time consuming (creating and crossing raster, normalizing datas,...).
To be more efficient and to able to replicate easily the methods using different parameters, I start to wrote some python scripts. At the end, we decided to port my scripts in a reusable plugin that can be use by any hydrogeologist with minimum knowledge of GIS software. I began this work during my internship but I lacked time to finish... After a couple of month, I found a job where I was able to keep working on it thanks to a financial support by UMR EMMAH, SNO KARST,... The plugin has been first published some months later. 
That was my first python plugin for QGIS and if you read a little the source code, you will see that a lot of things can be refactored and improved... Now, I'm a little bit more experienced and I have my own company so it can be easy for me to work on all that if I can find some money to support the project.
I made an estimation of the financial needs to port the plugin to QGIS 3 but i'm still waiting the answer about that to start working. I planned to take advantages of this migration to refactor and improve things in the code to make the tools more usable and flexible.
I can't see any problem to start a new branch if you want to works on it and share your results, I will really appreciate to works with contributors on this project ( Even more if these contributors have build the Paprika method ). I just need to ask the people that had put money here to get their agreement.
Don't hesitate to contact me in private (we can speak french for simplicity), you will find my phone number and mail adress here : [Contact](http://cartyl.fr/index.php/contact/).

**Comment by Yolecomte** [comment]
I just take some time to investigate a little bit more on this migration. After running qgis2to3 and qgis2apifinder on the Paprika Plugin. It appears that the core functionality doesn't need a huge work to be ported. The biggest part to handle is to make all processing calls compatible (the processing framework has changed a lot between qgis2 and qgis3...).

**Comment by Paprika-plugins** [comment]
Hi,

We finally get some money to do the job.
I have started working on the migration. I don't know exactly when I will publish a usable QGIS3 version but work is on progress ;)

**Comment by Yolecomte** [comment]
master has been updated to working version in QGIS3. Any tester or reviewer are welcome :)

**Comment by sylsta** [comment]
Congratulations ! 
I hope I'll find time to run some calculations and then to give feedback.
All the best :)

**Comment by Yolecomte** [comment]
The paprika toolbox is now available for Qgis3+ on official qgis plugins repository.
