### ISSUE TITLE
Edit the Ka factor interface and change the corresponding algorithms to skip Mangin index

### ISSUE THREAD

**Issue by Kolliv** [Paprika-plugins/PaPRIKa#5]
1/ Ka factor : supprimer l'algorithme de conversion depuis l'index de Mangin vers l'index de vulnérabilité, remplacer par "Global vulnerability index after system hydrological behavior" + une note : "please refere to plug manual to see usual rules to convert Mangin index into vulneraility index".

**Comment by Yolecomte** [comment]
Ok, it will simplify the code of the Carte_Ka.py algorithm. It's not a big deal.
We also need to change the UI (name of the combobox and text) and the PDF doc.

**Comment by Kolliv** [comment]
I modify the help file in accordance to the code.

**Comment by Kolliv** [comment]
2/ il est possible de sélectionner karst feature ou non, mais il n'y a pas besoins de spécifiez le champ indice, etant donné que la présence de karst feature doit automatiquement attribué l'indice 4 .

**Comment by Yolecomte** [comment]
Ca parait logique!
