### ISSUE TITLE
Improve the user experience by automating the calculation of Final map ponderation

### ISSUE THREAD

**Issue by Kolliv** [Paprika-plugins/PaPRIKa#7]
Final map : modify ponderation case , the last one should be automatically computed and suggested after the three other weights.

**Comment by Yolecomte** [comment]
If the 4 ponderations widget are filled and one is modified, how we have to deal with the three others to make sure that the total is 100%?

**Comment by Kolliv** [comment]
So , how does it work now ?

**Comment by Yolecomte** [comment]
Final choice goes to add a dynamic label below spinbox that shows the current sum of all ponderation.
In addition, the Run is disabled when this sum is different of 100...
